apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-dvwa
  labels:
    app: web-dvwa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-dvwa
  template:
    metadata:
      labels:
        app: web-dvwa
    spec:
      containers:
      - name: web-dvwa
        image: vulnerables/web-dvwa
        ports:
        - containerPort: 80
